<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<RootNamespace>DuckovCustomModel</RootNamespace>
		<AssemblyName>DuckovCustomModel</AssemblyName>
	</PropertyGroup>

	<PropertyGroup>
		<DuckovPath>D:\Saved Games\Platforms\Steam\steamapps\common\Escape from Duckov</DuckovPath>
	</PropertyGroup>

	<PropertyGroup>
		<UseGameLibsFromNuGet Condition="'$(CI)' == 'true' OR '$(GITHUB_ACTIONS)' == 'true' OR '$(UseGameLibsFromNuGet)' == 'true'">true</UseGameLibsFromNuGet>
		<UseGameLibsFromNuGet Condition="'$(UseGameLibsFromNuGet)' == ''">false</UseGameLibsFromNuGet>
	</PropertyGroup>

	<!-- CI 环境使用 NuGet 包 -->
	<ItemGroup Condition="'$(UseGameLibsFromNuGet)' == 'true'">
		<PackageReference Include="DuckovGameLibs" Version="2.0.26-Steam"/>
	</ItemGroup>

	<!-- 本地开发使用游戏目录 -->
	<ItemGroup Condition="'$(UseGameLibsFromNuGet)' == 'false'">
		<Reference Include="$(DuckovPath)\Duckov_Data\Managed\TeamSoda.*">
			<Private>False</Private>
		</Reference>
		<Reference Include="$(DuckovPath)\Duckov_Data\Managed\Unity*">
			<Private>False</Private>
		</Reference>
	</ItemGroup>

</Project>
